version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: idna
    versions:
    - "3.1"
  - dependency-name: urllib3
    versions:
    - 1.26.3
